export const cities = [
  'Abu Dhabi',
  'Abuja',
  'Accra',
  'Adamstown',
  'Addis Ababa',
  'Algiers',
  'Alofi',
  'Amman',
  'Amsterdam',
  'Andorra la Vella',
  'Ankara',
  'Antananarivo',
  'Apia',
  'Ashgabat',
  'Asmara',
  'Asunción',
  'Athens',
  'Avarua',
  'Baghdad',
  'Baku',
  'Bamako',
  'Bandar Seri Begawan',
  'Bangkok',
  'Bangui',
  'Banjul',
  'Basse-Terre',
  'Basseterre',
  'Beijing',
  'Beirut',
  'Belgrade',
  'Belmopan',
  'Berlin',
  'Bern',
  'Bishkek',
  'Bissau',
  'Bogota',
  'Brades',
  'Brasilia',
  'Bratislava',
  'Brazzaville',
  'Bridgetown',
  'Brussels',
  'Bucharest',
  'Budapest',
  'Buenos Aires',
  'Bujumbura',
  'Cairo',
  'Canberra',
  'Caracas',
  'Castries',
  'Cayenne',
  'Charlotte Amalie',
  'Chisinau',
  'Cockburn Town',
  'Colombo',
  'Conakry',
  'Concelho de Macau',
  'Copenhagen',
  'Dakar',
  'Damascus',
  'Dhaka',
  'Dili',
  'Djibouti City',
  'Dodoma',
  'Doha',
  'Douglas',
  'Dublin',
  'Dushanbe',
  'El Aaiún',
  'Flying Fish Cove',
  'Fort-de-France',
  'Freetown',
  'Funafuti',
  'Gaborone',
  'George Town',
  'Georgetown',
  'Gibraltar',
  'Guatemala City',
  'Gustavia',
  'Hagåtña',
  'Hamilton',
  'Hanoi',
  'Harare',
  'Havana',
  'Helsinki',
  'Hong Kong',
  'Honiara',
  'Islamabad',
  'Jakarta',
  'Jamestown',
  'Jerusalem (resp. Tel Aviv)',
  'Juba',
  'Kabul',
  'Kampala',
  'Kathmandu',
  'Khartoum',
  'Kigali',
  'King Edward Point',
  'Kingston',
  'Kingston',
  'Kingstown',
  'Kinshasa',
  'Kuala Lumpur',
  'Kuwait City',
  'Kyiv',
  'Libreville',
  'Lilongwe',
  'Lima',
  'Lisbon',
  'Ljubljana',
  'Lomé',
  'London',
  'Longyearbyen',
  'Luanda',
  'Lusaka',
  'Luxembourg',
  'Madrid',
  'Majuro',
  'Malabo',
  'Malé',
  'Mamoudzou',
  'Managua',
  'Manama',
  'Manila',
  'Maputo',
  'Mariehamn',
  'Marigot',
  'Maseru',
  'Mata-Utu',
  'Mbabane',
  'Mexico City',
  'Minsk',
  'Mogadishu',
  'Monaco',
  'Monrovia',
  'Montevideo',
  'Moroni',
  'Moscow',
  'Muscat',
  "N'Djamena",
  'Nairobi',
  'Nassau',
  'Nay Pyi Taw',
  'New Delhi',
  'Niamey',
  'Nicosia',
  'Nouakchott',
  'Nouméa',
  'Nuku‘alofa',
  'Nursultan',
  'Nuuk',
  'Oranjestad',
  'Oslo',
  'Ottawa',
  'Ouagadougou',
  'Pago Pago',
  'Panama City',
  'Papeete',
  'Paramaribo',
  'Paris',
  'Philipsburg',
  'Phnom Penh',
  'Podgorica',
  'Port Louis',
  'Port Moresby',
  'Port-au-Prince',
  'Port-of-Spain',
  'Port-Vila',
  'Porto-Novo',
  'Prague',
  'Praia',
  'Pretoria',
  'Pristina',
  'Pyongyang',
  'Quito',
  'Rabat',
  'Ramallah (resp. East Jerusalem)',
  'Reykjavík',
  'Riga',
  'Riyadh',
  'Road Town',
  'Rome',
  'Roseau',
  "Saint George's",
  'Saint Helier',
  'Saint John’s',
  'Saint Peter Port',
  'Saint-Denis',
  'Saint-Pierre',
  'Saipan',
  'San José',
  'San Juan',
  'San Marino',
  'San Salvador',
  'Sanaa',
  'Santiago',
  'Santo Domingo',
  'São Tomé',
  'Sarajevo',
  'Seoul',
  'Singapore',
  'Skopje',
  'Sofia',
  'Stanley',
  'Stockholm',
  'Sucre',
  'Suva',
  'Taipei',
  'Tallinn',
  'Tarawa',
  'Tashkent',
  'Tbilisi',
  'Tegucigalpa',
  'Tehran',
  'The Valley',
  'Thimphu',
  'Tirana',
  'Tokyo',
  'Tórshavn',
  'Tripoli',
  'Tunis',
  'Ulaanbaatar',
  'Vaduz',
  'Valletta',
  'Vatican City',
  'Victoria',
  'Vienna',
  'Vientiane',
  'Vilnius',
  'Warsaw',
  'Washington, D.C.',
  'Wellington',
  'West Island',
  'Willemstad',
  'Windhoek',
  'Yamoussoukro',
  'Yaounde',
  'Yaren',
  'Yerevan',
  'Zagreb',
];
